name: Request deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: bluwy/substitute-string-action@v1
        id: event_name
        with:
          _input-text: ${{ github.event.repository.name }}
          python.pizza: ""
      - name: Dispatch deploy request
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          event-type: prod_push
          repository: pythonpizza/infrastructure
          client-payload: '{"repository": "${{ github.event.repository.name }}", "event": "${{ steps.event_name.outputs.result }}", "domain": "${{ steps.event_name.outputs.result }}", "sha": "${{ github.sha }}"}'
